# User settings for the ultrasound air image analysis:
path_data: 'data\Z50\75L38EA'                                             # Directory location for analysis data
path_save: 'results\Z50\75L38EA'                                          # Directory location for storing results
file_name: !!null None

circle_fitfrac: !!float 0.33333333
vcor_px: !!int 0
hcor_px: !!int 0
box_x0y0x1y1: [60,118,581,500]
box_param_x0y0x1y1: [668,148,720,235]
signal_thresh: !!float 0
crop_depth: !!int 50
window: !!int 5
normalize_mode: !!null None
remove_small_clusers: False
num_reverb_lines: !!int 3
peak_height: !!float 0.1
peak_prominence: !!float .05

# Meta_data variable names:
transducer_type: '75L38EA'
