# User settings for the ultrasound air image analysis:
path_data: 'data'                                             # Directory location for analysis data
path_save: 'results'                                          # Directory location for storing results
file_name: 'data1.dcm'
meta_data_name: 'meta_data.yaml'


auto_suffix: False
circle_fitfrac: !!float 0.33333333
cluster_fminsize: !!int 300
f_dead: !!float 0.3
f_weak: !!float 0.5
vcor_px: !!int 0
hcor_px: !!int 0
x0y0x1y1: !!null None
init_x0x1: [37, 830]
init_y0y1: [90, 400]
signal_thresh: !!float 0
curve_radii_px: !!null None
curve_origin_px: !!null None
curve_angles_deg: !!null None
crop_depth: !!int 100
window: !!int 5
normalize_mode: 'normal'
