# User settings for the ultrasound air image analysis:
path_data: 'data\DC40\7L4B'                                             # Directory location for analysis data
path_save: 'results\DC40\7L4B'                                          # Directory location for storing results
file_name: 'thumbnail.bmp'
meta_data_name: 'DcmRegionPara.txt'

auto_suffix: False
circle_fitfrac: !!float 0.33333333
vcor_px: !!int 0
hcor_px: !!int 0
box_x0y0x1y1: [171,150,928,890]
box_param_x0y0x1y1: [1110,147,1300,322]
init_x0x1: !!null None
init_y0y1: !!null None
signal_thresh: !!float 05
crop_depth: !!int 50
window: !!int 5
normalize_mode: !!null None
remove_small_clusers: False
num_reverb_lines: !!int 3
peak_height: !!float 0.1
peak_prominence: !!float .05

# Meta_data variable names:
transducer_type: 'strProbeName'
Phys_units_X: 'PhyUnitsX'
Phys_units_Y: 'PhyUnitsY'
Phys_delta_X: 'PhyDeltaX'
Phys_delta_Y: 'PhyDeltaY'
